id = "nord"
name = "Nord Themes"
version = "0.1.2"
schema_version = 1
authors = ["Sergei Metlenkin <s.metlenkin@gmail.com>"]
description = "Nord color schemes for Zed. Includes light and dark variants."
repository = "https://github.com/mikasius/zed-nord-theme"
